# Generated by Django 5.0.1 on 2024-04-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0002_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
