# Generated by Django 5.0 on 2024-04-25 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_alter_contactmessage_options_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='donation_cards/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'DonationCard',
            },
        ),
    ]
