# Generated by Django 5.0 on 2024-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_feedback_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='feedback',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
