# Generated by Django 5.0 on 2024-04-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0006_rename_feedback_text_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('payment_option', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=10)),
            ],
        ),
    ]
